apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: appointments
          image: appointments:0.0.1-SNAPSHOT
          ports:
            - containerPort: 5004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentials
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: credentials
          image: credentials:0.0.1-SNAPSHOT
          ports:
            - containerPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: employee
          image: employee:0.0.1-SNAPSHOT
          ports:
            - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: location
          image: location:0.0.1-SNAPSHOT
          ports:
            - containerPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-records
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: patient-records
          image: patient-records:0.0.1-SNAPSHOT
          ports:
            - containerPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: gateway
          image: gateway:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  type: NodePort
  ports:
    - port: 6004
      targetPort: 5004
      nodePort: 30081
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: credentials
spec:
  type: NodePort
  ports:
    - port: 6002
      targetPort: 5002
      nodePort: 30082
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  type: NodePort
  ports:
    - port: 6001
      targetPort: 5001
      nodePort: 30083
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: location
spec:
  type: NodePort
  ports:
    - port: 6005
      targetPort: 5005
      nodePort: 30084
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: patient-records
spec:
  type: NodePort
  ports:
    - port: 6003
      targetPort: 5003
      nodePort: 30085
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - port: 6006
      targetPort: 9999
      nodePort: 30086
  selector:
    component: web