version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - 5672:15672
  employee: # <--- this is the name of the service and should be unique.
    image: employee:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: employee # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8081:5001 # <-- bind the host port 8083 to whatever is running in the container on 8080.
  credentials: # <--- this is the name of the service and should be unique.
    image: credentials:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: credentials # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8082:5002 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  patient-records: # <--- this is the name of the service and should be unique. 
    image: patient-records:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: patient-records # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8083:5003 # <-- bind the host port 8083 to whatever is running in the container on 8080.
  appointments: # <--- this is the name of the service and should be unique.
    image: appointments:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: appointments # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8084:5004 # <-- bind the host port 8082 to whatever is running in the container on 8080.
  location: # <--- this is the name of the service and should be unique.
    image: location:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: location # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8085:5005 # <-- bind the host port 8083 to whatever is running in the container on 8080.
  gateway: # <--- this is the name of the service and should be unique.
    image: gateway:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: gateway # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8888:9999 # <-- bind the host port 8888 to whatever is running in the container on 9999.
